require("wip_rice/wibar/widget/battery_widget")
require("wip_rice/wibar/widget/usage")
require("wip_rice/wibar/widget/internet")
require("wip_rice/wibar/widget/bluetooth")
require("wip_rice/wibar/widget/sound")
require("wip_rice/wibar/widget/separator")
require("wip_rice/wibar/widget/calendar_widget")
require("wip_rice/wibar/widget/brightness")
