icons = {}

icons.battery_full_discharging           = "󰁹"
icons.battery_90percent_discharging      = "󰂂"
icons.battery_80percent_discharging      = "󰂁"
icons.battery_70percent_discharging      = "󰂀"
icons.battery_60percent_discharging      = "󰁿"
icons.battery_50percent_discharging      = "󰁾"
icons.battery_40percent_discharging      = "󰁽"
icons.battery_30percent_discharging      = "󰁼"
icons.battery_20percent_discharging      = "󰁻"
icons.battery_10percent_discharging      = "󰁺"
icons.battery_00percent_discharging      = "󰂎"

icons.battery_full_charging           = "󰂅"
icons.battery_90percent_charging      = "󰂋"
icons.battery_80percent_charging      = "󰂊"
icons.battery_70percent_charging      = "󰢞"
icons.battery_60percent_charging      = "󰂉"
icons.battery_50percent_charging      = "󰢝"
icons.battery_40percent_charging      = "󰂈"
icons.battery_30percent_charging      = "󰂇"
icons.battery_20percent_charging      = "󰂆"
icons.battery_10percent_charging      = "󰢜"
icons.battery_00percent_charging      = "󰢟"

